# Generated by Django 4.0 on 2024-02-21 18:49

from django.db import migrations, models
import django.utils.timezone
import users.mixins
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ci', models.CharField(max_length=256, unique=True)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('hashed_email', models.CharField(max_length=256, unique=True)),
                ('username', models.BinaryField()),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('phone', models.BinaryField()),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('detail_address', models.BinaryField(blank=True, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=256, null=True)),
                ('detail_shipping_address', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(users.mixins.DeidentificationMixin, models.Model),
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
