# Generated by Django 4.0 on 2024-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_stock_product_quantity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_created_at_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='prod_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-created_at'], name='cat_prod_created_at_idx'),
        ),
    ]
