# Generated by Django 4.0 on 2024-02-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_product_prod_created_at_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='prod_created_at_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-deleted_at', '-created_at', 'selling'], name='prod_created_at_idx'),
        ),
    ]
