# Generated by Django 4.0 on 2024-02-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='cat_prod_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='prod_created_at_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-deleted_at', '-created_at', 'selling'], name='prod_selling_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-deleted_at', 'category', '-created_at'], name='prod_as_category_idx'),
        ),
    ]
