# Generated by Django 4.0 on 2024-02-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='count',
            new_name='quantity',
        ),
    ]
