# Generated by Django 4.0 on 2024-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_count_productorder_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productorder',
            constraint=models.UniqueConstraint(fields=('order_id', 'product_id'), name='unique_order_product_id'),
        ),
    ]
