# Generated by Django 4.0 on 2024-02-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productorder_unique_order_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detail_shipping_address',
            field=models.BinaryField(default=b'11'),
            preserve_default=False,
        ),
    ]
