# Generated by Django 4.0 on 2024-02-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_detail_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, '주문 시작'), (2, '결제 완료'), (3, '배송중'), (4, '배송 완료')], default=1, max_length=20),
        ),
    ]
