# Generated by Django 4.0 on 2024-02-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '주문 시작'), (2, '결제 완료'), (3, '배송중'), (4, '배송 완료')], default=1),
        ),
    ]
